Method 2: Using Torch

In [1]:
import torch

In [2]:
data = {
    'text': [
        "I love this product",
        "This is terrible",
        "The weather is great today",
        "I am feeling happy"
    ],
    "Sentimnet": [5,1,4,5] #Sentiment Score
}


importing nltk tokenizer

In [3]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [4]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [5]:
sentence_tokens = [word_tokenize(sentence.lower()) for sentence in data['text']]
sentence_tokens

[['i', 'love', 'this', 'product'],
 ['this', 'is', 'terrible'],
 ['the', 'weather', 'is', 'great', 'today'],
 ['i', 'am', 'feeling', 'happy']]

Word Representation

In [6]:
!pip install gensim

In [7]:
!pip install --upgrade numpy
!pip install --upgrade --force-reinstall gensim

  Using cached numpy-2.2.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Using cached numpy-2.2.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.2.4 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.4 which is incompatible.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 2.2.4 which is incompatible.
  Using cached gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (

In [8]:
import gensim
from gensim.models import Word2Vec
import numpy as np

In [9]:
vectorization_model = Word2Vec(sentences = sentence_tokens, vector_size = 5, min_count = 1, workers = 4)

In [10]:
def get_sentence_embedding(sentence, vectorization_model):
  words = word_tokenize(sentence.lower())
  embeddings = np.mean([vectorization_model.wv[word] for word in words if word in vectorization_model.wv], axis =0)
  return embeddings

In [11]:
sentence_embeddings = np.array([get_sentence_embedding(sentence, vectorization_model) for sentence in data['text']])
sentence_embeddings

array([[-0.02888067,  0.04882137, -0.03245607, -0.04846277, -0.00366516],
       [-0.05299478, -0.00643957,  0.15794054,  0.05983936, -0.02555452],
       [-0.11685958,  0.03145216,  0.03005491, -0.03759657, -0.02843774],
       [ 0.05469256,  0.07245404, -0.01358971, -0.00461568, -0.06355911]],
      dtype=float32)

In [12]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
x = torch.tensor(sentence_embeddings, device=device, dtype=torch.float32, requires_grad = True)
x

tensor([[-0.0289,  0.0488, -0.0325, -0.0485, -0.0037],
        [-0.0530, -0.0064,  0.1579,  0.0598, -0.0256],
        [-0.1169,  0.0315,  0.0301, -0.0376, -0.0284],
        [ 0.0547,  0.0725, -0.0136, -0.0046, -0.0636]], device='cuda:0',
       requires_grad=True)

In [13]:
y = torch.tensor(data['Sentimnet'], device=device, dtype=torch.float32, requires_grad = True)
y

tensor([5., 1., 4., 5.], device='cuda:0', requires_grad=True)