Import

In [1]:
import torch

In [2]:
torch.__version__

'2.6.0+cu124'

Creating a Scalar

In [3]:
sca_lar = torch.tensor(987)
sca_lar.ndim
sca_lar.item()
sca_lar.size()

torch.Size([])

Creating a vector

In [4]:
vec_tor = torch.tensor([34,66])
# vector = torch.tensor([[7],
                      # [4]])
vec_tor.ndim
vec_tor.shape


torch.Size([2])

Creating a Matrix

In [5]:
mat_rix = torch.tensor([[13,24,83],
                         [49,59,36]])

mat_rix.ndim
mat_rix.shape

torch.Size([2, 3])

Tensor

In [6]:
Ten_sor = torch.tensor([[[4,4],[5,5],[6,6]],
                        [[7,7],[8,8],[9,9]],
                        [[4,4],[7,7],[1,1]]])
Ten_sor.ndim
Ten_sor.shape

torch.Size([3, 3, 2])

Creating Random, Ones and Zero Tensor

In [7]:
Rand_tensor = torch.rand(3,4)
Rand_tensor

tensor([[0.7872, 0.5586, 0.7353, 0.9260],
        [0.6706, 0.5332, 0.9581, 0.6805],
        [0.5273, 0.9612, 0.4759, 0.1867]])

In [8]:
Ones_tensor = torch.ones(3,4)
Ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
Zeros_tensor = torch.zeros(3,4)
Zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Float with CPU




In [10]:
# float_32_tensor = torch.tensor([8.9,6.66,98.009],
#                                dtype=torch.float32,
#                                device=None,
#                                requires_grad=False)
# float_32_tensor.dtype

Float with GPU

In [11]:
torch.cuda.is_available() # to check GPU availability

True

In [12]:
float_32_tensor = torch.tensor([8.9,6.66,98.009],
                               dtype=torch.float32,
                               device='cuda',
                               requires_grad=False)
float_32_tensor.dtype

torch.float32

In [13]:
print(float_32_tensor.ndim,
      float_32_tensor.size(),
      float_32_tensor.dtype,
      float_32_tensor.device)


1 torch.Size([3]) torch.float32 cuda:0


# Performing Mathematical functions

Addition

In [14]:
random1 = torch.rand(4,4)
random2 = torch.rand(4,4)
random1 + random2

tensor([[0.6455, 0.8348, 1.3871, 1.3475],
        [0.8212, 1.1976, 0.9069, 0.6200],
        [1.2256, 1.4578, 1.1488, 1.2194],
        [0.4210, 1.3181, 0.5658, 1.2569]])

Subtraction

In [15]:
random3 = torch.rand(5,2)
random4 = torch.rand(5,2)
random3 - random4

tensor([[-0.2585,  0.4354],
        [-0.4770,  0.2023],
        [-0.8097,  0.1488],
        [-0.3154, -0.4572],
        [ 0.5691,  0.4941]])

Division

In [16]:
random5 = torch.rand(3,3)
random6 = torch.rand(3,3)
random5 / random6

tensor([[0.3115, 6.1306, 0.2792],
        [0.6425, 0.0716, 0.7552],
        [0.4102, 1.1289, 1.5251]])

Multiplication

In [17]:
random7 = torch.rand(2,3)
random8 = torch.rand(3,8)
torch.matmul(random7,random8)

tensor([[0.2686, 0.7119, 0.8835, 0.3171, 0.3591, 0.7843, 0.6966, 0.6231],
        [0.5462, 1.2072, 1.3828, 0.5219, 0.5060, 1.0455, 0.8212, 0.9300]])

# Tensor Manipulation

Random seed

In [18]:
torch.manual_seed(seed=42)
tensaar = torch.rand(size=(3, 3, 5))
tensaar

tensor([[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
         [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
         [0.9346, 0.5936, 0.8694, 0.5677, 0.7411]],

        [[0.4294, 0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317, 0.1053],
         [0.2695, 0.3588, 0.1994, 0.5472, 0.0062]],

        [[0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
         [0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464, 0.7890]]])

In [19]:
# tensor = torch.arange(8)
tensor = torch.tensor([[4,4],[5,5],[6,6]])
tensor.shape

torch.Size([3, 2])

Reshape

In [20]:
# Adding a dimension
tensor.reshape(2,3)
# tensor

tensor([[4, 4, 5],
        [5, 6, 6]])

Unsqueeze

In [21]:
# adds a dimension as using reshape, can add one at a time
tensor.unsqueeze(2)

tensor([[[4],
         [4]],

        [[5],
         [5]],

        [[6],
         [6]]])

Squeeze

In [22]:
# Remove extra dimension
tensor.squeeze(1)

tensor([[4, 4],
        [5, 5],
        [6, 6]])

View

In [23]:
z = tensor.view(tensor.shape) # create a copy first
z

tensor([[4, 4],
        [5, 5],
        [6, 6]])

In [24]:
# now changing z changes vector
z[0] = 5
z, tensor

(tensor([[5, 5],
         [5, 5],
         [6, 6]]),
 tensor([[5, 5],
         [5, 5],
         [6, 6]]))

Permute

In [25]:
tensor.permute(1,0)

tensor([[5, 5, 6],
        [5, 5, 6]])

Stacking

In [26]:
rand1 = torch.rand(3,3)
rand2 = torch.rand(3,3)
rand3 = torch.rand(3,3)
rand4 = torch.rand(3,3)
torch.stack([rand1,rand2,rand3,rand4],dim=0)

tensor([[[0.2814, 0.7886, 0.5895],
         [0.7539, 0.1952, 0.0050],
         [0.3068, 0.1165, 0.9103]],

        [[0.6440, 0.7071, 0.6581],
         [0.4913, 0.8913, 0.1447],
         [0.5315, 0.1587, 0.6542]],

        [[0.3278, 0.6532, 0.3958],
         [0.9147, 0.2036, 0.2018],
         [0.2018, 0.9497, 0.6666]],

        [[0.9811, 0.0874, 0.0041],
         [0.1088, 0.1637, 0.7025],
         [0.6790, 0.9155, 0.2418]]])

In [27]:
x_stacked = torch.stack([rand1,rand2,rand3,rand4],dim=2)
x_stacked


tensor([[[0.2814, 0.6440, 0.3278, 0.9811],
         [0.7886, 0.7071, 0.6532, 0.0874],
         [0.5895, 0.6581, 0.3958, 0.0041]],

        [[0.7539, 0.4913, 0.9147, 0.1088],
         [0.1952, 0.8913, 0.2036, 0.1637],
         [0.0050, 0.1447, 0.2018, 0.7025]],

        [[0.3068, 0.5315, 0.2018, 0.6790],
         [0.1165, 0.1587, 0.9497, 0.9155],
         [0.9103, 0.6542, 0.6666, 0.2418]]])